apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: mahi-deployment
spec:
  selector:
    matchLabels:
      app: firsttry
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: firsttry
    spec:
      containers:
        - name: firsttry
          image: kasunurmahi/firsttry:latey # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: firsttry-ssvc
spec:
  selector:
    app: firsttry
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: LoadBalancer # type of the service.
